In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import torch
import einops
from transformers import AutoModelForCausalLM, AutoTokenizer
from dataclasses import dataclass
import os
import random

import mypkg.whitebox_infra.attribution as attribution
import mypkg.whitebox_infra.dictionaries.batch_topk_sae as batch_topk_sae
import mypkg.whitebox_infra.data_utils as data_utils
import mypkg.whitebox_infra.model_utils as model_utils
import mypkg.whitebox_infra.interp_utils as interp_utils
import mypkg.pipeline.setup.dataset as dataset_setup
import mypkg.pipeline.infra.hiring_bias_prompts as hiring_bias_prompts
from mypkg.eval_config import EvalConfig

/home/ubuntu/whitebox_evals/.venv/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [3]:
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
model_name = "mistralai/Ministral-8B-Instruct-2410"
# model_name = "mistralai/Mistral-Small-24B-Instruct-2501"
# model_name = "google/gemma-2-9b-it"
# model_name = "google/gemma-2-27b-it"

args = hiring_bias_prompts.HiringBiasArgs(
    political_orientation=True,
    employment_gap=False,
    pregnancy=False,
    race=False,
    gender=False,
)


# args = hiring_bias_prompts.HiringBiasArgs(
#     political_orientation=False,
#     employment_gap=False,
#     pregnancy=False,
#     race=True,
#     gender=False,
# )

dtype = torch.bfloat16
model = AutoModelForCausalLM.from_pretrained(
    model_name, torch_dtype=dtype, device_map=device
)
tokenizer = AutoTokenizer.from_pretrained(model_name)

gradient_checkpointing = False

if model_name == "google/gemma-2-27b-it":
    gradient_checkpointing = True
    batch_size = 1
elif model_name == "mistralai/Mistral-Small-24B-Instruct-2501":
    batch_size = 2
else:
    batch_size = 4

if gradient_checkpointing:
    model.config.use_cache = False
    model.gradient_checkpointing_enable()


chosen_layer_percentage = [25]
chosen_layer_percentage = [50]

chosen_layers = []
for layer_percent in chosen_layer_percentage:
    chosen_layers.append(model_utils.MODEL_CONFIGS[model_name]["layer_mappings"][layer_percent]["layer"])

eval_config = EvalConfig(
        model_name=model_name,
        political_orientation=True,
        pregnancy=False,
        employment_gap=False,
        anthropic_dataset=False,
        downsample=50,
        gpu_inference=True,
        anti_bias_statement_file="v1.txt",
        job_description_file="short_meta_job_description.txt",
        system_prompt_filename="yes_no.txt",
    )


Loading checkpoint shards: 100%|██████████| 4/4 [00:02<00:00,  1.34it/s]
You are using the default legacy behaviour of the <class 'transformers.models.llama.tokenization_llama_fast.LlamaTokenizerFast'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565 - if you loaded a llama tokenizer from a GGUF file you can ignore this message.


In [4]:
# sae_repo = "adamkarvonen/ministral_saes"
# sae_path = f"mistralai_Ministral-8B-Instruct-2410_batch_top_k/resid_post_layer_{chosen_layers[0]}/trainer_1/ae.pt"

# sae = batch_topk_sae.load_dictionary_learning_batch_topk_sae(
#     repo_id=sae_repo,
#     filename=sae_path,
#     model_name=model_name,
#     device=device,
#     dtype=dtype,
#     layer=chosen_layers[0],
#     local_dir="downloaded_saes",
# )
trainer_id = 3
sae = model_utils.load_model_sae(model_name, device, dtype, chosen_layer_percentage[0], trainer_id=trainer_id)

submodules = [model_utils.get_submodule(model, chosen_layers[0])]

Original keys in state_dict: dict_keys(['b_dec', 'k', 'threshold', 'decoder.weight', 'encoder.weight', 'encoder.bias'])
Renamed keys in state_dict: dict_keys(['b_dec', 'k', 'threshold', 'W_dec', 'W_enc', 'b_enc'])


In [5]:
df = dataset_setup.load_raw_dataset()

industry = "INFORMATION-TECHNOLOGY"
downsample = eval_config.downsample
random_seed = eval_config.random_seed

random.seed(random_seed)
torch.manual_seed(random_seed)

df = dataset_setup.filter_by_industry(df, industry)

df = dataset_setup.balanced_downsample(df, downsample, random_seed)



prompts = hiring_bias_prompts.create_all_prompts_hiring_bias(df, args, eval_config)

Downsampled to 50 unique resumes
Total samples after maintaining demographic variations: 200


In [6]:
train_texts, train_labels = hiring_bias_prompts.process_hiring_bias_resumes_prompts(prompts, args)

train_texts = model_utils.add_chat_template(train_texts, model_name)

dataloader = data_utils.create_simple_dataloader(
    train_texts, train_labels, model_name, device, batch_size=batch_size
)

No pad token found, setting eos token as pad token


In [7]:
diff_acts_F = attribution.get_activations(model, sae, dataloader, submodules, chosen_layers, device)

  0%|          | 0/100 [00:00<?, ?it/s]

100%|██████████| 100/100 [00:08<00:00, 12.38it/s]


In [ ]:
top_k_ids = diff_acts_F.abs().topk(20).indices
print(top_k_ids)

top_k_vals = diff_acts_F[top_k_ids]
print(top_k_vals)

output_filename = os.path.join(
    "diff_acts",
    f"{eval_config.anti_bias_statement_file.replace('.txt', '')}_trainer_{trainer_id}_model_{model_name.replace('/', '_')}_layer_{chosen_layer_percentage[0]}_attrib_data.pt",
)
print(output_filename)

os.makedirs("diff_acts", exist_ok=True)

diff_acts = {"diff_acts_F": diff_acts_F}
diff_acts["config"] = {
        "model_name": model_name,
        "layer": chosen_layers[0],
        "bias_categories": "N\A",
        "anti_bias_statement_file": eval_config.anti_bias_statement_file,
        "downsample": eval_config.downsample,
        "random_seed": eval_config.random_seed,
        "batch_size": batch_size,
        "chosen_layer_percentage": chosen_layer_percentage,
        "trainer_id": trainer_id,
    }

torch.save(diff_acts, output_filename)

# tensor([23759, 42925, 33394, 45780, 10085, 23574, 30460, 61472,   521, 59020,
#           775,  4261, 41205, 29588, 44488,   983, 55773, 44225, 42612, 30063],
#        device='cuda:0')
# tensor([-2.2821e-05, -1.8463e-05, -1.8400e-05,  1.6533e-05, -1.6091e-05,
#          1.5563e-05,  1.5402e-05,  1.4945e-05, -1.4770e-05, -1.4396e-05,
#         -1.4326e-05, -1.4277e-05, -1.3993e-05,  1.3824e-05, -1.3621e-05,
#         -1.2731e-05,  1.2631e-05,  1.2598e-05, -1.2597e-05, -1.2533e-05],
#        device='cuda:0')
# diff_acts/v1_trainer_3_model_mistralai_Ministral-8B-Instruct-2410_layer_50_attrib_data.pt

tensor([44488, 21402, 55027, 27261, 24536, 19628, 18223,  3488, 33556, 49973,
        46702,  6190, 56091, 11365,  2515, 33595, 56960, 19150,  1378, 36212],
       device='cuda:0')
tensor([-0.0005, -0.0003, -0.0003,  0.0003, -0.0002,  0.0002,  0.0002, -0.0002,
         0.0002, -0.0002,  0.0002, -0.0002, -0.0002,  0.0002, -0.0002,  0.0002,
        -0.0001,  0.0001, -0.0001, -0.0001], device='cuda:0')
diff_acts/v1_trainer_3_model_mistralai_Ministral-8B-Instruct-2410_layer_50_attrib_data.pt


In [9]:
set1 = set(top_k_ids.cpu().tolist())
set2 = set([ 4794,  4393, 15242,  2039,  9049,  3645, 11802,  9265,  7781, 13002,
        16078,  4204,   394,  5286, 11901,  7654, 13855,  3509,  9206,  1529])

print(set1)
print(set2)

print(set1.intersection(set2))

{56960, 33556, 21402, 56091, 3488, 19628, 6190, 18223, 49973, 33595, 44488, 19150, 2515, 24536, 1378, 11365, 46702, 55027, 36212, 27261}
{15242, 394, 11802, 13855, 5286, 4393, 9265, 3509, 4794, 3645, 13002, 16078, 9049, 7781, 7654, 4204, 9206, 2039, 1529, 11901}
set()


In [10]:
# Build the custom loss function
yes_vs_no_loss_fn = attribution.make_yes_no_loss_fn(
    tokenizer,
    yes_candidates=["yes", " yes", "Yes", " Yes", "YES", " YES"],
    no_candidates=["no", " no", "No", " No", "NO", " NO"],
    device=device,
)

effects_F, error_effect = attribution.get_effects(
    model,
    sae,
    dataloader,
    yes_vs_no_loss_fn,
    submodules,
    chosen_layers,
    device,
)

# Print peak memory usage
if torch.cuda.is_available():
    peak_memory = torch.cuda.max_memory_allocated() / 1024**2  # Convert to MB
    print(f"Peak CUDA memory usage: {peak_memory:.2f} MB")

# Peak CUDA memory usage: 33432.72 MB

  0%|          | 0/100 [00:00<?, ?it/s]

100%|██████████| 100/100 [00:24<00:00,  4.07it/s]

Peak CUDA memory usage: 29866.82 MB


In [11]:
top_k_ids = effects_F.abs().topk(20).indices
print(top_k_ids)

top_k_vals = effects_F[top_k_ids]
print(top_k_vals)

print(error_effect)

# tensor([ 4393, 15242,  9049,  3959, 11802, 14960,   428,  9920,  2715,  3509,
#          9444, 12979,  9319,  8910, 12243,  7781, 11637, 10283,  4204,  2557],
#        device='cuda:0')
# tensor([0.0074, 0.0058, 0.0033, 0.0016, 0.0016, 0.0013, 0.0011, 0.0009, 0.0008,
#         0.0008, 0.0008, 0.0008, 0.0007, 0.0007, 0.0007, 0.0007, 0.0006, 0.0006,
#         0.0006, 0.0005], device='cuda:0')

# tensor([ 4393, 15242,  9049, 13855, 11802,  3959,  2039, 14960,  1683,  3509,
#           428,  4794,  3645,  9920,  5911,  1160,  1656, 16078,  9319,   394],
#        device='cuda:0')
# tensor([ 0.0305,  0.0242,  0.0133, -0.0078,  0.0064,  0.0063, -0.0058,  0.0052,
#         -0.0051,  0.0050,  0.0045, -0.0043, -0.0042,  0.0040, -0.0039, -0.0034,
#         -0.0033, -0.0033,  0.0033, -0.0031], device='cuda:0')
# tensor(-0.0181, device='cuda:0')

# tensor([ 4393, 15242,  9049, 13855, 11802,  3645,  2039,  3959,  1683,  3509,
#         14960,  9920,  4794,  1656,  5911, 16078,  9319,  1160,  5286,   394],
#        device='cuda:0')
# tensor([ 0.0276,  0.0227,  0.0114, -0.0077,  0.0062, -0.0058, -0.0056,  0.0055,
#         -0.0049,  0.0047,  0.0046,  0.0038, -0.0036, -0.0035, -0.0034, -0.0034,
#          0.0033, -0.0032, -0.0030, -0.0029], device='cuda:0')
# tensor(-0.0127, device='cuda:0')

tensor([61846, 40367, 38432, 36372, 45780, 33394, 47800, 48455, 53058, 61440,
        51775, 56006, 38912,  1327, 61568, 35355,  4261, 12979, 49062, 42173],
       device='cuda:0')
tensor([ 0.0245,  0.0134,  0.0088, -0.0061,  0.0061, -0.0058, -0.0045, -0.0043,
        -0.0042,  0.0040, -0.0035,  0.0033,  0.0030, -0.0027,  0.0026, -0.0024,
         0.0024, -0.0024,  0.0022,  0.0021], device='cuda:0')
tensor(0.0216, device='cuda:0')


In [12]:
print(sae.W_dec.shape[0])

65536


In [13]:
acts_dir = "max_acts"
acts_filename = f"acts_{model_name}_layer_{chosen_layers[0]}_trainer_{trainer_id}_layer_percent_{chosen_layer_percentage[0]}.pt".replace("/", "_")
if not os.path.exists(acts_filename):
    from huggingface_hub import hf_hub_download
    path_to_config = hf_hub_download(
        repo_id="adamkarvonen/sae_max_acts",
        filename=acts_filename,
        force_download=False,
        local_dir=acts_dir,
        repo_type="dataset",
    )

    acts_path = os.path.join(acts_dir, acts_filename)
    acts_data = torch.load(acts_path)
    
    # max_tokens, max_acts = interp_utils.get_interp_prompts(
    #     model,
    #     submodules[0],
    #     sae,
    #     torch.tensor(list(range(sae.W_dec.shape[0]))),
    #     context_length=128,
    #     tokenizer=tokenizer,
    #     batch_size=batch_size * 32,
    #     num_tokens=30_000_000,
    # )
    # acts_data = {
    #     "max_tokens": max_tokens,
    #     "max_acts": max_acts,
    # }
    # torch.save(acts_data, acts_filename)
else:
    acts_path = os.path.join(acts_dir, acts_filename)
    acts_data = torch.load(acts_path)
max_tokens = acts_data["max_tokens"].cpu()
max_acts = acts_data["max_acts"].cpu()


In [ ]:
from circuitsvis.activations import text_neuron_activations
import gc
from IPython.display import clear_output, display

def _list_decode(x):
    if len(x.shape) == 0:
        return tokenizer.decode(x, skip_special_tokens=False)
    else:
        return [_list_decode(y) for y in x]
    

clear_output(wait=True)
gc.collect()

for i in range(10):
    feature_idx = top_k_ids[i]
    feature_val = top_k_vals[i]
    print(f"Feature {i}, value: {feature_val}")
    selected_token_KL = max_tokens[feature_idx]

    selected_activations_KL11 = [max_acts[feature_idx, k, :, None, None] for k in range(5)]
    selected_token_strs_KL = _list_decode(selected_token_KL)

    for k in range(len(selected_token_strs_KL)):
        if "<s>" in selected_token_strs_KL[k][0] or "<bos>" in selected_token_strs_KL[k][0]:
            selected_token_strs_KL[k][0] = "BOS>"

    # selected_token_strs_KL = tokenizer.batch_decode(selected_token_KL, skip_special_tokens=False)
    # for k in range(len(selected_token_strs_KL)):
    #     string = selected_token_strs_KL[k]
    #     print(string[:10])
        # print("".join(string))

    html_activations = text_neuron_activations(selected_token_strs_KL, selected_activations_KL11)
    display(html_activations)

Feature 0, value: 0.024504682049155235


Feature 1, value: 0.013357884250581264


Feature 2, value: 0.00882805697619915


Feature 3, value: -0.00612232182174921


Feature 4, value: 0.006070456001907587


Feature 5, value: -0.005834635812789202


Feature 6, value: -0.004539120011031628


Feature 7, value: -0.004254115279763937


Feature 8, value: -0.004236398730427027


Feature 9, value: 0.003994414582848549


Feature 10, value: -0.0034573315642774105


Feature 11, value: 0.003282492747530341


Feature 12, value: 0.002999071031808853


Feature 13, value: -0.0027022664435207844


Feature 14, value: 0.002606120426207781


Feature 15, value: -0.002427060855552554


Feature 16, value: 0.0024179904721677303


Feature 17, value: -0.002353836316615343


Feature 18, value: 0.002156444825232029


Feature 19, value: 0.0021032639779150486
